app:
  build: .
  command: bundle exec rails s -p 3000
  ports:
    - "3000:3000"
  volumes:
    - .:/usr/src/app
  links:
    - db

db:
  image: postgres:9.4
  volumes:
    - ztl_db:/var/lib/postgresql/data
