app:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  ports:
    - "3000:3000"
  volumes:
    - .:/usr/src/app
  links:
    - db
    - mailcatcher

db:
  image: postgres:9.4
  volumes:
    - ztl_db:/var/lib/postgresql/data

mailcatcher:
  image: schickling/mailcatcher
  ports:
    - "1080:1080"
